Payment:
  supported_methods:
    - 'DirectCreditPayment' : 'Direct Credit Payment'
    - 'DirectCreditPayment_ViaCheque' : 'Direct Credit Payment'
    - 'DirectCreditPayment_ViaCreditCart' : 'Direct Credit Payment'
    - 'DirectCreditPayment_ViaCreditCart' : 'OffLine Credit Card'
    - 'DirectCreditPayment_TESTSUCCESS' : 'Test Successful Payment'
    - 'DirectCreditPayment_TESTFAILURE' : 'Test Failed Payment'
